### ISSUE TITLE
CRAN error

### ISSUE THREAD

**Issue by martinamorris** [statnet/statnet#1]
https://www.r-project.org/nosvn/R.check/r-oldrel-windows-ix86+x86_64/statnet-00check.html

```
Error: package or namespace load failed for 'ergm' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace 'Matrix' 1.2-15 is being loaded, but >= 1.2.17 is required
Error: package 'ergm' could not be loaded
Execution halted
```

**Comment by martinamorris** [comment]
This is from the 3.5.3 version of R, so may not be problem, but wanted to check

**Comment by skhan890** [comment]
It looks like it's loading Matrix 1.2-15, but needs 1.2.17. According to the [Matrix package documentation](https://cran.r-project.org/web/packages/Matrix/index.html), having R v.3.5.3 shouldn't be an issue. (it needs R ≥ 3.2.0).

I never submitted to CRAN, so I'm not sure how it installs and loads packages - does it install the .tar of your package onto a CRAN VM of some sort, and installs all the packages/dependencies itself - or does it model itself off of your environment?

**Comment by martinamorris** [comment]
> It looks like it's loading Matrix 1.2-15, but needs 1.2.17. According to the Matrix package documentation,
> having R v.3.5.3 shouldn't be an issue. (it needs R ≥ 3.2.0).

yes, that much i gathered from the error message itself...

> I never submitted to CRAN, so I'm not sure how it installs and loads packages - does it install the .tar of
> your package onto a CRAN VM of some sort, and installs all the packages/dependencies itself - or does it
> model itself off of your environment?

we had a similar issue arise with tergm when i tested statnet last week 
(that one concerned the nlme package: 
https://github.com/statnet/tergm/pull/8).  Pavel fixed it but I'm not sure 
how

**Comment by martinamorris** [comment]
Note that the travis build is also failing.

**Comment by chad-klumb** [comment]
looks like the `tergm` issue was fixed by lowering the `nlme` version requirement in the `tergm` `DESCRIPTION` file

did that require you to push a new version of `tergm` to CRAN, in order to get `statnet` through?

in principle the same thing could be tried for `Matrix`, assuming `ergm` can actually run correctly with 1.2.15

discussion of this issue

https://github.com/travis-ci/travis-ci/issues/5756

suggests that (someone else's) `nlme` version problems may be due to `base` R recommending `nlme` so an earlier version gets attached

**Comment by martinamorris** [comment]
> looks like the tergm issue was fixed by lowering the nlme version requirement in the tergm DESCRIPTION file
> did that require you to push a new version of tergm to CRAN, in order to get statnet through?

yes.  and that's why i had to wait for so long to submit statnet.

> in principle the same thing could be tried for Matrix, assuming ergm can actually run correctly with 1.2.15
> discussion of this issue
> travis-ci/travis-ci#5756
> suggests that (someone else's) nlme version problems may be due to base R recommending nlme so an earlier
> version gets attached

oh jeez.  that suggests this must be a fairly common problem.  basically, 
no packages can get out ahead of what base R depends on, even if they need 
the new functionality in an updated package?

**Comment by martinamorris** [comment]
@chad-klumb can you pls check my edits to the travis.yml file 57569b0f9c54038dcc19450ed99f631e0f291d7f and see if they make sense?

**Comment by chad-klumb** [comment]
looks okay to me but might be linux-specific; mac appears to use different directories

CRAN doesn't go through travis, does it?

**Comment by chad-klumb** [comment]
btw here's a list of "recommended" packages (note that both `Matrix` and `nlme` are there):

https://stackoverflow.com/questions/9700799/difference-between-r-base-and-r-recommended-packages

**Comment by martinamorris** [comment]
> CRAN doesn't go through travis, does it?

i don't think so.

i'm still wondering why we're only getting this error with statnet, not with `ergm` itself, since `ergm`  depends on R, so it should trigger the same version conflict for `Matrix`.

**Comment by chad-klumb** [comment]
that is a good question and I don't know the answer; maybe Pavel does :)
