### ISSUE TITLE
can't install statnet-dependency tergm

### ISSUE THREAD

**Issue by reprep52** [statnet/statnet#3]
Trying to install statnet/tergm I get following error:
_ERROR: compilation failed for package ‘tergm’
* removing ‘/home/ep/R/x86_64-pc-linux-gnu-library/4.1/tergm’
Warning in install.packages :
  installation of package ‘/home/ep/Schreibtisch/tergm_3.7.0.tar.gz’ had non-zero exit status_
I'm working on linux-mint with RStudio Version 1.4.1717 and R Version 1.4.1717. I tryed to install from R Studio (repository and package archive file) and from the R Consol. 
Ruedi

**Comment by krivit** [comment]
Thank you for the report. We are in the middle of updating the suite, and an update to `tergm` will be released shortly.
