### ISSUE TITLE
Request for a public statnet/sna repository 

### ISSUE THREAD

**Issue by facorread** [statnet/statnet#4]
Hi all,

This is a request for a public `sna` repository at [github.com/statnet](https://github.com/statnet).

The public repositories at [https://github.com/statnet](github.com/statnet) are excellent places for learning all Statnet packages; the workshops have a lot of information but sometimes there are details that can only be understood after diving into the source code; this is also true with recently updated packages such as [`ergm`](https://github.com/statnet/ergm).

I wanted to understand the internals of some functions in the `sna` package, including the `degree(cmode = "freeman")` algorithm. Unfortunately, there is no public `sna` repository.

I speculate there is some private `sna` repository here on GitHub, and I was hoping to see you making it public if possible. I figured creating an issue in this repository would be acceptable.

Thanks,
Fabio

**Comment by mbojan** [comment]
@facorread , the `sna` package was developed by @CarterButts  long before Statnet came to be (I believe it is more than two decades now). I don't think he keeps the sources on GitHub. Still, every R package is open source and `sna` is no exception -- every functions' source code is accessible. You have two basic options:

1. If you work with RStudio, just type the function name in the editor, put a cursor on it and press F2. You'll see the source code of that function in a new tab. That should be more convenient than just typing `degree` in the console.
2. Download the *source* version of the package as a tar with
    ```r
    download.packages("sna", ".", type="source")
    ```
    Untar and browse. The advantage is the files will have all the comments which are stripped in (1) above.
