### ISSUE TITLE
Which residuals from netlogit?

### ISSUE THREAD

**Issue by FCalderoni** [statnet/statnet#8]
I am struggling to identify the type of residuals stored by netlogit output. 

Below a reprex, where I compare the netlogit's residuals with raw residuals, Pearson's residuals and deviance residuals. They do not match.
Thanks for any feedback. 

`# ========================= LRQAP Residual Analysis ============================
# Load required libraries
library(sna)
library(igraph)

# ---------------------------- Data Setup --------------------------------------
# Create example symmetric (undirected) binary adjacency matrices
set.seed(123)

# Generate random binary matrices and make them symmetric
make_symmetric <- function(mat) {
  mat[lower.tri(mat)] <- t(mat)[lower.tri(mat)]
  diag(mat) <- 0
  return(mat)
}

# Dependent variable (undirected binary adjacency matrix)
dependent_matrix <- matrix(rbinom(100, 1, 0.2), nrow = 10)
dependent_matrix <- make_symmetric(dependent_matrix)

# Independent variables (undirected binary adjacency matrices)
independent_matrix_1 <- matrix(rbinom(100, 1, 0.3), nrow = 10)
independent_matrix_2 <- matrix(rbinom(100, 1, 0.4), nrow = 10)
independent_matrix_1 <- make_symmetric(independent_matrix_1)
independent_matrix_2 <- make_symmetric(independent_matrix_2)

# Combine into a list for LRQAP
independent_matrices <- list(independent_matrix_1, independent_matrix_2)

# -------------------------- Run netlogit --------------------------------------
# Fit the LRQAP model
model <- netlogit(
  y = dependent_matrix,           # Dependent matrix
  x = independent_matrices,       # List of independent matrices
  intercept = TRUE,               # Include intercept
  mode = "graph",
  nullhyp = "qap",                # QAP null hypothesis
  reps = 1000                     # Number of permutations
)

# Print model summary
print(summary(model))

# ------------------------- Extract Residuals ----------------------------------
# Extract residuals computed by netlogit
netlogit_residuals <- model$residuals

# ----------------------- Compute Residuals Manually ---------------------------
# Observed values (vectorized lower triangle of the dependent matrix)
observed <- dependent_matrix[lower.tri(dependent_matrix)]

# Predicted probabilities from the model (vectorized lower triangle)
fitted_probs <- model$fitted.values[lower.tri(dependent_matrix)]

# Raw Residuals: observed - predicted
raw_residuals <- observed - fitted_probs

# Pearson Residuals: normalized residuals
pearson_residuals <- (observed - fitted_probs) / sqrt(fitted_probs * (1 - fitted_probs))

# Deviance Residuals: based on log-likelihood differences
deviance_residuals <- sign(observed - fitted_probs) *
  sqrt(-2 * (observed * log(fitted_probs) + (1 - observed) * log(1 - fitted_probs)))

# ----------------------- Compare Residuals ------------------------------------
# Combine residuals into a data frame for comparison
residuals_comparison <- data.frame(
  Observed = observed,                  # Observed values
  Fitted_Probs = fitted_probs,          # Predicted probabilities
  Netlogit_Residuals = netlogit_residuals,  # Residuals from netlogit
  Raw_Residuals = raw_residuals,        # Manually computed raw residuals
  Pearson_Residuals = pearson_residuals,# Manually computed Pearson residuals
  Deviance_Residuals = deviance_residuals # Manually computed deviance residuals
)

# Display the first few rows of the residual comparison
print(head(residuals_comparison))

# Check which residuals from netlogit match manually computed residuals
raw_match <- all.equal(netlogit_residuals, raw_residuals)
pearson_match <- all.equal(netlogit_residuals, pearson_residuals)
deviance_match <- all.equal(netlogit_residuals, deviance_residuals)

cat("Match with Raw Residuals:", raw_match, "\n")
cat("Match with Pearson Residuals:", pearson_match, "\n")
cat("Match with Deviance Residuals:", deviance_match, "\n")

# ======================= End of LRQAP Residual Analysis =======================
`

**Comment by krivit** [comment]
Package `sna` is not currently hosted on GitHub and is not supported here. Your best bet is to subscribe to the [statnet help mailing list](http://mailman13.u.washington.edu/mailman/listinfo/statnet_help) and ask there.
